#:kivy 1.0.9

<SpaceGame>:
    player: spaceship

    Label:
        font_size: 20
        center_x: root.width / 4
        top: root.top - 10
        text: "Score: "

    Label:
        font_size: 20
        center_x: root.width * 3 / 4
        top: root.top - 10
        text: "Lives: "


<Alien>:

    size: 35, 35
    canvas:
        Rectangle:
            pos: self.pos
            size: self.size
            source: 'alien1.png'